In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r"F:\Je respire\トレーニング後\統合データ\tobii_data_20260121_130428.csv")

In [9]:
df["Marker"][15876]

'Marker:2'

In [19]:
df.iloc[13793:15876].tail()

,device_time_stamp,system_time_stamp,pc_time_stamp,left_x,left_y,right_x,right_y,left_pupil,right_pupil,left_validity,right_validity,blink,Marker
15871,2437773865,1768967002,1768967002,0.495440,0.341821,0.491957,0.356457,3.386749,3.207596,1,1,False,NaN
15872,2437782198,1768967002,1768967002,0.498934,0.353290,0.492142,0.348025,3.396713,3.200272,1,1,False,NaN
15873,2437790531,1768967002,1768967002,0.497684,0.345931,0.487470,0.350076,3.386398,3.203568,1,1,False,NaN
15874,2437798868,1768967002,1768967002,0.496175,0.342362,0.490297,0.352483,3.399368,3.204681,1,1,False,NaN
15875,2437807201,1768967002,1768967002,0.484343,0.344053,0.496070,0.356264,3.379166,3.196152,1,1,False,NaN

In [21]:
"""
1768966985	Marker:1	13795
1768967002	Marker:2	15878
1768967016	Marker:3	17562
1768967028	Marker:4	19035
1768967045	Marker:5	21021
1768967079	Marker:6	25158
1768967129	Marker:7	31118
1768967150	Marker:8	33662
1768967197	Marker:9	39251
1768967205	Marker:10	40271
1768967245	Marker:11	45007
1768967270	Marker:12	48002
1768967286	Marker:13	49979
1768967297	Marker:14	51336
1768967344	Marker:15	56909
1768967373	Marker:16	60388
1768967384	Marker:17	61759
1768967414	Marker:18	65330
1768967426	Marker:19	66767
1768967442	Marker:20	68708
1768967472	Marker:21	72286
1768967488	Marker:22	74255
1768967510	Marker:23	76822
1768967538	Marker:24	80151
1768967593	Marker:25	86816
1768967622	Marker:26	90320
1768967733	Marker:27	103628
1768967910	Marker:28	124832
1768967945	Marker:29	128998
1768968001	Marker:30	135775
1768968141	Marker:31	152551
1768968186	Marker:32	157970
1768968221	Marker:33	162183
1768968253	Marker:34	165996

"""

'\n1768966985\tMarker:1\t13795\n1768967002\tMarker:2\t15878\n1768967016\tMarker:3\t17562\n1768967028\tMarker:4\t19035\n1768967045\tMarker:5\t21021\n1768967079\tMarker:6\t25158\n1768967129\tMarker:7\t31118\n1768967150\tMarker:8\t33662\n1768967197\tMarker:9\t39251\n1768967205\tMarker:10\t40271\n1768967245\tMarker:11\t45007\n1768967270\tMarker:12\t48002\n1768967286\tMarker:13\t49979\n1768967297\tMarker:14\t51336\n1768967344\tMarker:15\t56909\n1768967373\tMarker:16\t60388\n1768967384\tMarker:17\t61759\n1768967414\tMarker:18\t65330\n1768967426\tMarker:19\t66767\n1768967442\tMarker:20\t68708\n1768967472\tMarker:21\t72286\n1768967488\tMarker:22\t74255\n1768967510\tMarker:23\t76822\n1768967538\tMarker:24\t80151\n1768967593\tMarker:25\t86816\n1768967622\tMarker:26\t90320\n1768967733\tMarker:27\t103628\n1768967910\tMarker:28\t124832\n1768967945\tMarker:29\t128998\n1768968001\tMarker:30\t135775\n1768968141\tMarker:31\t152551\n1768968186\tMarker:32\t157970\n1768968221\tMarker:33\t162183\n1768968253\tMarker:34\t165996\n\n'

In [30]:
i=2
df.iloc[165996-i:].head()

,device_time_stamp,system_time_stamp,pc_time_stamp,left_x,left_y,right_x,right_y,left_pupil,right_pupil,left_validity,right_validity,blink,Marker
165994,3688838836,1768968253,1768968253,0.496765,0.489460,0.466829,0.465038,3.502777,3.367706,1,1,False,Marker:34
165995,3688847169,1768968253,1768968253,0.490582,0.467686,0.469465,0.481469,3.467667,3.355637,1,1,False,NaN
165996,3688855502,1768968253,1768968253,0.500608,0.469613,0.479785,0.467779,3.478088,3.333603,1,1,False,NaN
165997,3688863836,1768968253,1768968253,0.496944,0.461921,0.476193,0.474742,3.455017,3.348190,1,1,False,NaN
165998,3688872169,1768968253,1768968253,0.496554,0.461628,0.471904,0.478386,3.459045,3.348694,1,1,False,NaN

In [31]:
i = 2
with pd.ExcelWriter(r"F:\Je respire\トレーニング後\統合データ\output.xlsx") as writer:
    df.iloc[13793:15876].to_excel(writer, sheet_name="1", index=False)
    df.iloc[15876:17560].to_excel(writer, sheet_name="2", index=False)
    df.iloc[17560:19033].to_excel(writer, sheet_name="3", index=False)
    df.iloc[19033:21021-i].to_excel(writer, sheet_name="4", index=False)
    df.iloc[21021-i:25158-i].to_excel(writer, sheet_name="5", index=False)
    df.iloc[25158-i:31118-i].to_excel(writer, sheet_name="6", index=False)
    df.iloc[31118-i:33662-i].to_excel(writer, sheet_name="7", index=False)
    df.iloc[33662-i:39251-i].to_excel(writer, sheet_name="8", index=False)
    df.iloc[39251-i:40271-i].to_excel(writer, sheet_name="9", index=False)
    df.iloc[40271-i:45007-i].to_excel(writer, sheet_name="10", index=False)
    df.iloc[45007-i:48002-i].to_excel(writer, sheet_name="11", index=False)
    df.iloc[48002-i:49979-i].to_excel(writer, sheet_name="12", index=False)
    df.iloc[49979-i:51336-i].to_excel(writer, sheet_name="13", index=False)
    df.iloc[51336-i:56909-i].to_excel(writer, sheet_name="14", index=False)
    df.iloc[56909-i:60388-i].to_excel(writer, sheet_name="15", index=False)
    df.iloc[60388-i:61759-i].to_excel(writer, sheet_name="16", index=False)
    df.iloc[61759-i:65330-i].to_excel(writer, sheet_name="17", index=False)
    df.iloc[65330-i:66767-i].to_excel(writer, sheet_name="18", index=False)
    df.iloc[66767-i:68708-i].to_excel(writer, sheet_name="19", index=False)
    df.iloc[68708-i:72286-i].to_excel(writer, sheet_name="20", index=False)
    df.iloc[72286-i:74255-i].to_excel(writer, sheet_name="21", index=False)
    df.iloc[74255-i:76822-i].to_excel(writer, sheet_name="22", index=False)
    df.iloc[76822-i:80151-i].to_excel(writer, sheet_name="23", index=False)
    df.iloc[80151-i:86816-i].to_excel(writer, sheet_name="24", index=False)
    df.iloc[86816-i:90320-i].to_excel(writer, sheet_name="25", index=False)
    df.iloc[90320-i:103628-i].to_excel(writer, sheet_name="26", index=False)
    df.iloc[103628-i:124832-i].to_excel(writer, sheet_name="27", index=False)
    df.iloc[124832-i:128998-i].to_excel(writer, sheet_name="28", index=False)
    df.iloc[128998-i:135775-i].to_excel(writer, sheet_name="29", index=False)
    df.iloc[135775-i:152551-i].to_excel(writer, sheet_name="30", index=False)
    df.iloc[152551-i:157970-i].to_excel(writer, sheet_name="31", index=False)
    df.iloc[157970-i:162000-i].to_excel(writer, sheet_name="32", index=False)
    df.iloc[162183-i:165996-i].to_excel(writer, sheet_name="33", index=False)
    df.iloc[165996-i:].to_excel(writer, sheet_name="34", index=False)