# トレーニング効果の検証に向けた統計検定

In [1]:
import pandas as pd

In [4]:
df = pd.read_excel(r"F:\Je respire\トレーニング後\1.3 脳血流と問題カテゴリの関連 - 背外側追加 - メンタル指標追加.xlsx", sheet_name="ディアビアイ")

In [5]:
df.head()

,subject,question,q_category,score,left_pupil_std,right_pupil_std,CH1_std,CH2_std,CH3_std,CH4_std,...,CD_RISC_total,CD_RISC_reading,CD_RISC_memory,CD_RISC_recognition,CD_RISC_attention,SRS_18,ERQ_reevaluation_total,ERQ_reevaluation_ave,ERQ_suppression_total,ERQ_suppression_ave
0,1,15,3,2,0.198059,-0.004101,-0.023247,0.063408,-0.052554,-0.538870,...,38.0,6.0,12.0,6.0,5.0,26.0,24.0,4.0,11.0,2.75
1,1,1,1,2,0.269850,0.237645,0.074821,0.562988,-0.036988,-0.567791,...,38.0,6.0,12.0,6.0,5.0,26.0,24.0,4.0,11.0,2.75
2,1,11,2,1,0.747078,0.743156,-0.042180,0.689511,-0.107446,0.053479,...,38.0,6.0,12.0,6.0,5.0,26.0,24.0,4.0,11.0,2.75
3,1,4,1,2,-0.047677,-0.082496,0.014693,-0.313235,0.032525,0.923615,...,38.0,6.0,12.0,6.0,5.0,26.0,24.0,4.0,11.0,2.75
4,1,18,3,0,0.185023,0.105690,-0.005959,-0.735926,0.043048,0.346212,...,38.0,6.0,12.0,6.0,5.0,26.0,24.0,4.0,11.0,2.75

3(nagashio) before 48-71, after 264-287  
4(yanaze) before 72-95, after 240-263

In [9]:
df[48:72].tail()

,subject,question,q_category,score,left_pupil_std,right_pupil_std,CH1_std,CH2_std,CH3_std,CH4_std,...,CD_RISC_total,CD_RISC_reading,CD_RISC_memory,CD_RISC_recognition,CD_RISC_attention,SRS_18,ERQ_reevaluation_total,ERQ_reevaluation_ave,ERQ_suppression_total,ERQ_suppression_ave
67,3,22,4,2,-0.036676,0.040174,-0.138460,-0.309018,-1.267885,-0.731588,...,74.0,14.0,16.0,15.0,15.0,4.0,36.0,6.0,22.0,5.5
68,3,16,3,2,0.246321,0.208165,-0.054078,0.416498,-0.957715,-0.000038,...,74.0,14.0,16.0,15.0,15.0,4.0,36.0,6.0,22.0,5.5
69,3,23,4,0,-0.487284,-0.459813,0.166164,-0.500447,-1.252104,-1.956051,...,74.0,14.0,16.0,15.0,15.0,4.0,36.0,6.0,22.0,5.5
70,3,9,2,2,-0.460698,-0.341451,-0.031591,-0.524147,-1.210571,-0.757195,...,74.0,14.0,16.0,15.0,15.0,4.0,36.0,6.0,22.0,5.5
71,3,3,1,2,-0.464691,-0.545639,0.035168,-0.368079,-1.102230,-1.263075,...,74.0,14.0,16.0,15.0,15.0,4.0,36.0,6.0,22.0,5.5

In [11]:
df_right_haigai_before = df["right_haigai"].iloc[48:72].tail()
# df_right_haigai_after = df["right_haigai"].iloc[264:288]