# トレーニング効果の検証に向けた統計検定

In [2]:
import pandas as pd

In [3]:
df = pd.read_excel(r"F:\Je respire\トレーニング後\トレーニング前後比較.xlsx")

In [4]:
df.head()

,subject,question,q_category,score,left_pupil_std,right_pupil_std,CH1_std,CH2_std,CH3_std,CH4_std,...,CD_RISC_total,CD_RISC_reading,CD_RISC_memory,CD_RISC_recognition,CD_RISC_attention,SRS_18,ERQ_reevaluation_total,ERQ_reevaluation_ave,ERQ_suppression_total,ERQ_suppression_ave
0,3,1,1,2,0.380827,0.271983,1.182634,0.973981,0.840443,1.517479,...,74,14,16,15,15,4,36,6.0,22,5.5
1,3,8,2,2,-0.462448,-0.538958,0.595958,1.009921,0.026125,0.973451,...,74,14,16,15,15,4,36,6.0,22,5.5
2,3,5,1,2,-0.140344,-0.147450,1.080476,1.173780,0.203121,0.862638,...,74,14,16,15,15,4,36,6.0,22,5.5
3,3,21,4,2,1.092684,1.000796,1.524975,1.466847,0.091430,0.200126,...,74,14,16,15,15,4,36,6.0,22,5.5
4,3,18,3,0,0.271099,0.159905,1.500132,1.677728,0.280140,0.307397,...,74,14,16,15,15,4,36,6.0,22,5.5

3(nagashio) before 0-23, after 72-95  
4(yanaze) before 24-47, after 48-71

In [6]:
df_before = df.iloc[0:48]
df_after = df.iloc[48:96]

In [11]:
df_after.tail()

,subject,question,q_category,score,left_pupil_std,right_pupil_std,CH1_std,CH2_std,CH3_std,CH4_std,...,CD_RISC_total,CD_RISC_reading,CD_RISC_memory,CD_RISC_recognition,CD_RISC_attention,SRS_18,ERQ_reevaluation_total,ERQ_reevaluation_ave,ERQ_suppression_total,ERQ_suppression_ave
91,3_2,1,1,2,0.360090,0.292606,-1.382977,-0.368862,-0.815615,-0.393965,...,72,13,15,15,15,3,33,5.5,23,5.75
92,3_2,9,2,2,-0.258818,-0.328705,-1.418517,-0.784160,-1.095582,-0.709014,...,72,13,15,15,15,3,33,5.5,23,5.75
93,3_2,18,3,2,-0.252674,-0.363038,-1.010152,-0.391844,-1.179098,-0.875616,...,72,13,15,15,15,3,33,5.5,23,5.75
94,3_2,13,3,0,0.467650,0.390016,-0.932460,-0.149038,-0.961132,-1.017652,...,72,13,15,15,15,3,33,5.5,23,5.75
95,3_2,20,4,1,0.452234,0.462808,-0.121156,-0.030608,-0.267256,-0.180819,...,72,13,15,15,15,3,33,5.5,23,5.75